name: Build latest image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Docker Login
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        args: -p bugs --timeout=3m

    - name: Build and push Docker image
      run: |
        docker build -t ghcr.io/metal-stack/audit-forwarder .
        docker push ghcr.io/metal-stack/audit-forwarder

    - uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
